name: Node.js CI (Vérification Automatique)

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Étape 1 : Lancer une base de données PostgreSQL temporaire
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: fadel_user
          POSTGRES_PASSWORD: fadel_password
          POSTGRES_DB: fadel_db_test
        ports:
          - 5432:5432
        # On attend que la DB soit prête avant de lancer les tests
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 📁 Récupération du code
        uses: actions/checkout@v4

      - name: 🟢 Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 📦 Installation des dépendances
        run: npm ci

      - name: 🔐 Fix permissions binaire Prisma
        run: chmod +x ./node_modules/.bin/prisma || true

      - name: 💎 Génération du client Prisma
        run: npx prisma generate
        env:
          # On passe une URL fictive juste pour la génération
          DATABASE_URL: postgresql://fadel_user:fadel_password@localhost:5432/fadel_db_test

      - name: 🔄 Appliquer les migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: postgresql://fadel_user:fadel_password@localhost:5432/fadel_db_test

      - name: 🧪 Lancement des tests d'intégration
        run: npm test
        env:
          # Ici, ton fichier prisma.config.ts et buildDatabaseUrl liront cette URL
          DATABASE_URL: postgresql://fadel_user:fadel_password@localhost:5432/fadel_db_test
          JWT_SECRET: ${{ secrets.JWT_SECRET_TEST }}
          NODE_ENV: test