name: Node.js CI (Vérification Automatique)

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Récupération du code
      uses: actions/checkout@v4

    - name: 🟢 Configuration de Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: 📦 Installation des dépendances
      run: npm install

    - name: 💎 Génération du client Prisma
      run: npx prisma generate

    - name: 🧪 Lancement des tests d'intégration
      run: npm test
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL_TEST }}
        JWT_SECRET: ${{ secrets.JWT_SECRET_TEST }}
