name: Flutter CI (Mobile Verification)

on:
  pull_request:
    branches: [ develop ]
    paths:
      - 'mobile/**' # Ne se lance que si des fichiers dans le dossier mobile changent

jobs:
  mobile-tests:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 🐦 Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    - name: 📦 Install dependencies
      run: flutter pub get
      working-directory: ./mobile

    - name: 🔍 Check formatting
      run: flutter format --set-exit-if-changed .
      working-directory: ./mobile

    - name: 🛡️ Analyze code (Lint)
      run: flutter analyze
      working-directory: ./mobile

    - name: 🧪 Run tests
      run: flutter test
      working-directory: ./mobile
